### ISSUE TITLE
Allow setting payment-config in node-types

### ISSUE THREAD

**Issue by zakaprov** [golemfactory/goth#565]
Currently, in `goth-config.yml`, payment platforms to be used are defined individually for each node, for example:
```
nodes:

  - name: "requestor"
    type: "Requestor"
    payment-config: "erc20"

  - name: "provider-1"
    type: "VM-Wasm-Provider"
    payment-config: "erc20"

```

It would be useful to enable setting this for a given node type defined in the config file, for example:
```
node-types:
  # Each node type is a collection of attributes common to a group of nodes.
  # Required attributes are "name" and "class".

  - name: "Requestor"
    class: "goth.runner.probe.RequestorProbe"
    payment-config: "erc20"
```
